### ISSUE TITLE
인터페이스 1, 2 중 선택

### ISSUE THREAD

**Issue by kjmin622** [kjmin622/ERICA_Game_DevilInvade#2]
1.
![image](https://user-images.githubusercontent.com/50573808/68418057-dec25f00-01da-11ea-9f7f-2070e8709c5a.png)

2.
![image](https://user-images.githubusercontent.com/50573808/68418026-ce11e900-01da-11ea-9d01-6fba1f1d2631.png)

**Comment by huskycat1202** [comment]
2!!! 캐릭터를 조금 더 세밀하게 표현하고 싶어요!

**Comment by kjmin622** [comment]
2로 설정
