### ISSUE TITLE
Bullet 어떻게 짜야할까

### ISSUE THREAD

**Issue by kjmin622** [kjmin622/ERICA_Game_DevilInvade#3]
지금 필요해 보이는 것
Move 상속 (x,y, direction, speed)
damage 
width
height

피격판정 메소드

**Comment by huskycat1202** [comment]
effect는 사이즈 얼마로 생각중?

**Comment by kjmin622** [comment]
- width, height
+ radius = 8

**Comment by kjmin622** [comment]
완료
