### ISSUE TITLE
floor 해결좀

### ISSUE THREAD

**Issue by huskycat1202** [kjmin622/ERICA_Game_DevilInvade#6]
floor 에서 random으로 방 구현중인데 문제가 너무 많아..
1. 무한생성
2. 보스가 들어갈 특정방 구현(보스방은 입구가 하나여야해)
3. 방들이 다 뭉쳐있는것!!(=보스방 없는것)
4. 방개수 결정하기

**Comment by kjmin622** [comment]
1. 배열  초기화가 안됐었엉
2. 입구가 하나인 방을 찾아서 랜덤
3. 4개 정사각형 모양 방 없애는걸로 해결가능
4.  bfs에 횟수제한을 두면 됨

**Comment by kjmin622** [comment]
무한생성 -> 방 들어갈때마다 몹 새로 생성함으로 해결
이하 위와 동일
